imgapp: heic-decode: make help the default option
Tested:

Before:
```
$ ~/proj/imgapp/scripts/heic-decode.py
Traceback (most recent call last):
  File "/home/chemag/proj/imgapp/scripts/heic-decode.py", line 368, in <module>
    main(sys.argv)
  File "/home/chemag/proj/imgapp/scripts/heic-decode.py", line 357, in main
    decode_heic_using_imgapp(options.infile, options.outfile, options.inPreferredColorSpace, options.tmpdir, options.debug)
  File "/home/chemag/proj/imgapp/scripts/heic-decode.py", line 172, in decode_heic_using_imgapp
    infile_name = os.path.split(infile)[1]
                  ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 103, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

After:
```
$ ~/proj/imgapp/scripts/heic-decode.py
usage: heic-decode.py [-h] [-d] [--quiet] [--proc [help | decode | analyze]] [--width WIDTH] [--height HEIGHT] [--size SIZE]
                      [--inPreferredColorSpace [ACES | ACESCG | ADOBE_RGB | BT2020 | BT2020_HLG | BT2020_PQ | BT709 | CIE_LAB | CIE_XYZ | DCI_P3 | DISPLAY_P3 | EXTENDED_SRGB | LINEAR_EXTENDED_SRGB | LINEAR_SRGB | NTSC_1953 | PRO_PHOTO_RGB | SMPTE_C | SRGB | None]]
                      [--tmpdir TMPDIR] [-i input-file] [-o output-file]

heic-decode.py A test for android HEIC decoding. The first function is decode heic files in an android device. The script copies a heic file into an android device, and then calls imgapp
to read it (using `BitmapFactory.decodeFile()`) into a `Bitmap`. Finally, it converts the `Bitmap` pixel information (packed ARGB) into a packed RGBA file, which is the output file. The
second function analyzes a heic file (or set of heic files) providing the average and variance of each of the color components (R, G, B, and A).

options:
  -h, --help            show this help message and exit
  -d, --debug           Increase verbosity (use multiple times for more)
  --quiet               Zero verbosity
  --proc [help | decode | analyze]
                        processing
  --width WIDTH         use WIDTH width (default: -1)
  --height HEIGHT       HEIGHT height (default: -1)
  --size SIZE           use <width>x<height>
  --inPreferredColorSpace [ACES | ACESCG | ADOBE_RGB | BT2020 | BT2020_HLG | BT2020_PQ | BT709 | CIE_LAB | CIE_XYZ | DCI_P3 | DISPLAY_P3 | EXTENDED_SRGB | LINEAR_EXTENDED_SRGB | LINEAR_SRGB | NTSC_1953 | PRO_PHOTO_RGB | SMPTE_C | SRGB | None]
                        inPreferredColorSpace parameter
  --tmpdir TMPDIR       TMPDIR tmpdir (default: /sdcard)
  -i input-file, --infile input-file
                        input file
  -o output-file, --outfile output-file
                        output file
```